# Generated by Django 4.2.11 on 2024-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_captchadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='password',
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='user_otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
