# Generated by Django 4.2.11 on 2024-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=90)),
                ('author_name', models.CharField(max_length=90)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
